version: "3.8"

services:
  database:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
     PGADMIN_DEFAULT_EMAIL: 111@gmail.com
     PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "10000:80"
    depends_on:
      - database

  web-app:
    build:
      context: .
    ports:
      - "8080:8000"
    restart: always
    volumes:
      - ./library:/library
    environment:
      - DB_HOST=database
      - DB_NAME=db
      - DB_USER=root
      - DB_PASSWORD=root
    depends_on:
      - database
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

  redis:
    image: redis:7.0.5-alpine
    hostname: redis

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./library:/library
    environment:
      - DB_HOST=database
      - DB_NAME=db
      - DB_USER=root
      - DB_PASSWORD=root
    depends_on:
      - database
      - redis
    links:
      - redis

  worker2:
    build:
      context: .
    hostname: worker2
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./library:/library
    environment:
      - DB_HOST=database
      - DB_NAME=db
      - DB_USER=root
      - DB_PASSWORD=root
    depends_on:
      - database
      - redis
    links:
      - redis

  flower:
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - ./library:/library
    depends_on:
      - database
      - redis
    links:
      - redis
    ports:
      - '5555:5555'