version: "3.8"

services:
  database:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
     PGADMIN_DEFAULT_EMAIL: 111@gmail.com
     PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "50600:80"